version: '2'
services:
  wordpress:
    build: .
    env_file: .env
    volumes:
      - /Sites:/var/www/html/
    ports:
      - "80:80"
    links:
      - mysql
      - redis
  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    command: crond -f -l 6 -L /dev/stdout
    volumes:
      - /Sites:/var/www/html/
      - ./mysqldumps:/usr/local/mysql
    env_file: .env
    links:
      - mysql
      - redis
  mysql:
    build:
       context: .
       dockerfile: Dockerfile-mysql 
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqldumps:/usr/local/mysql
    env_file: .env-mysql
  redis:
    image: redis:3.2.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
